INSERT INTO announcements(id_user, post_date, end_date, current_status, title, content) VALUES
(1, '2017-01-25', NULL ,'w trakcie', 'Pomogę osobom starszym','Pomoc doraźna, pomoc ludziom starszym'),
(2, '2016-07-14', '2016-07-19','w trakcie', 'Potrzebna opieka dla córki','Chora córka po wypadku. Złamane wszystkie żebra'),
(2, '2017-03-01', '2017-03-14','w trakcie', 'Potrzebna opieka','Niedowład nóg, przekuplina oraz uraz psychiczny'),
(3, '2014-05-29', '2014-06-11','zakończony', 'Potrzebuję pomocy w poruszaniu się','Złamane obie nogi, spadł z drabiny'),
(4, '2017-09-25', NULL,'w trakcie', 'Pomogę osobom starszym', 'Co mogę to pomogę'),
(4, '2014-11-24', NULL,'zakończone','Pomogę w codziennych czynnościach','Pomoc w robieniu zakupów i wyprowadzaniu psa'),
(5, '2017-01-11', NULL,'w trakcie', 'Potrzebuję pomocy w poruszaniu się','Osoba leżąca, niedowład nóg po wypadku samochodowym'),
(1, '2015-12-25', NULL,'w trakcie', 'Potrzebuję pomocy w codziennych czynnościach','Osoba niepełnosprawna jeżdżąca na wózku'),
(2, '2017-06-01', NULL,'zakończony', 'Zajmę się osobami starszymi','Rozmowa z osobami starszymi, odwiedzanie, pomoc psychologiczna'),
(4, '2016-07-25', '2016-08-01','zakończony', 'Potrzebuję pomocy w poruszaniu się','Skręcona kostka, pomoc w robieniu zakupów'),
(8, '2017-03-12', NULL,'w trakcie',  'Potrzebna ciągła opieka','Nietrzymanie moczu, pomoc w utrzymaniu higieny osobistej'),
(12, '2015-01-21', NULL,'w trakcie',  'Organizacja zbiórek','Organizacja zbiórek pieniędzy, imprez charytatywnych'),
(4, '2016-07-25', NULL,'zakończony', 'Pomogę w codziennych czynnościach', 'pomoc w robieniu zakupów'),
(12, '2017-07-05', NULL,'zakończony', 'Pomogę w codziennych czynnościach','pomoc w robieniu zakupów'),
(8, '2016-11-14', NULL,'w trakcie','Potrzebuję pomocy w poruszaniu się','Skręcona kostka, pomoc w robieniu zakupów'),
(14, '2017-09-11', NULL,'zakończony',  'Potrzebuję pomocy w poruszaniu się','Skręcona kostka, pomoc w robieniu zakupów'),
(15, '2017-01-15', NULL,'w trakcie', 'Potrzebuję pomocy w poruszaniu się','Skręcona kostka, pomoc w robieniu zakupów'),
(16, '2017-05-12', NULL,'w trakcie',  'Pomogę w codziennych czynnościach', 'pomoc w robieniu zakupów'),
(17, '2014-07-04', NULL,'zakończony', 'Pomogę w codziennych czynnościach','pomoc w robieniu zakupów'),
(1, '2015-06-27', NULL,'w trakcie', 'Potrzebuję pomocy w poruszaniu się','Skręcona kostka, pomoc w robieniu zakupów'),
(19, '2016-07-10', NULL,'w trakcie', 'Potrzebuję pomocy w poruszaniu się','Skręcona kostka, pomoc w robieniu zakupów');
