INSERT INTO announcements(post_date, end_date, created_by, current_status, type, content) VALUES
('2017-01-25', NULL, 'Birdie','w trakcie', 'volunteer', 'Pomoc doraźna, pomoc ludziom starszym'),
('2016-07-14', '2016-07-19','Lolek','w trakcie', 'needy', 'Chora córka po wypadku. Złamane wszystkie żebra'),
('2017-03-01', '2017-03-14','Micha1','w trakcie', 'needy', 'Niedowład nóg, przekuplina oraz uraz psychiczny'),
('2014-05-29', '2014-06-11','Sztazi','zakończony', 'needy', 'Złamane obie nogi, spadł z drabiny'),
('2017-09-25', NULL,'Rzolniez18','w trakcie', 'volunteer', 'Co mogę to pomogę'),
('2014-11-24', NULL,'LubiePiwo','zakończone', 'volunteer', 'Pomoc w robieniu zakupów i wyprowadzaniu psa'),
('2017-01-11', NULL,'Luksusowa40','w trakcie', 'needy', 'Osoba leżąca, niedowład nóg po wypadku samochodowym'),
('2015-12-25', NULL,'Tyskie24','w trakcie', 'needy', 'Osoba niepełnosprawna jeżdżąca na wózku'),
('2017-06-01', NULL, 'ZielonyBeret','zakończony', 'volunteer', 'Rozmowa z osobami starszymi, odwiedzanie, pomoc psychologiczna'),
('2016-07-25', '2016-08-01', 'MalyKomandos','zakończony', 'needy', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2017-03-12', NULL, 'Damian34','w trakcie', 'needy', 'Nietrzymanie moczu, pomoc w utrzymaniu higieny osobistej'),
('2015-01-21', NULL,'Dziku','w trakcie', 'volunteer', 'Organizacja zbiórek pieniędzy, imprez charytatywnych'),
('2016-07-25', NULL,'Katol12','zakończony', 'volunteer', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2017-07-05', NULL, 'Kopacky_R','zakończony', 'volunteer', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2016-11-14', NULL, 'Oshee','w trakcie', 'needy', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2017-09-11', NULL, 'Dajesc.mi','zakończony', 'needy', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2017-01-15', NULL,'Monoza','w trakcie', 'needy', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2017-05-12', NULL,'Zanaldestroyer123','w trakcie', 'volunteer', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2014-07-04', NULL,'Zmechol1999','zakończony', 'volunteer', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2015-06-27', NULL,'Cybernetyk2014','w trakcie', 'needy', 'Skręcona kostka, pomoc w robieniu zakupów'),
('2016-07-10', NULL,'Applefan','w trakcie', 'needy', 'Skręcona kostka, pomoc w robieniu zakupów');
